import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans, Bitter } from "next/font/google";
import SiteHeader from "@/components/layout/SiteHeader";

const open_sans = Open_Sans({ subsets: ["latin"] });
const bitter = Bitter({ subsets: ["latin"], variable: "--google-font-bitter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} ${bitter.variable}`}>
        <SiteHeader></SiteHeader>
        {children}
      </body>
    </html>
  );
}
